---
namespace: "tcharl"
name: "ansible_hostname"
version: "0.0.1"
description: "Configures etc/host file on systems"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible-hostname"
documentation: "https://github.com/OsgiliathEnterprise/ansible-hostname/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/ansible-hostname"
issues: "https://github.com/OsgiliathEnterprise/ansible-hostname/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "etchost"
  - "host"
